modLoader="javafml" #mandatory
loaderVersion="[33,37)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GPLv3"
[[mods]] #mandatory
modId="konkrete" #mandatory
version="1.1.3" #mandatory
displayName="Konkrete" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/konkrete" #optional
logoFile="konkrete.png" #optional
authors="Keksuccino" #optional
description='''

COPYRIGHT:

Konkrete Copyright © 2020-2021 Keksuccino.
Konkrete is licensed under GPLv3.

'''